name: Contact Manager Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'


      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-


      - name: Build Spring Boot App
        run: mvn clean package -DskipTests

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/contact-manager:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/contact-manager:latest

      - name: Deploy to Render
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{
                 "serviceId": "${{ secrets.RENDER_SERVICE_ID }}",
                 "envVars": {
                   "DB_URI": "${{ secrets.DB_URI }}",
                   "DB_USER": "${{ secrets.DB_USER }}",
                   "DB_PASS": "${{ secrets.DB_PASS }}"
                      }
                    }' \
                https://api.render.com/deploy/${{ secrets.RENDER_SERVICE_ID }}
